### ISSUE TITLE
AutoRom download fails to contact s2roms.cc

### ISSUE THREAD

**Issue by KaleabTessera** [PettingZoo-Team/AutoROM#8]
# Issue
AutoRom install appears to no longer work. Looks like the process fails to connect to s2roms.cc. 

# Full Stacktrace
Running `AutoRom -v` gives the following:
```
AutoROM will download the Atari 2600 ROMs in link_map.txt from atarimania.com and s2roms.cc. 
They will be installed to
        /home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/multi_agent_ale_py/ROM/
for use with Multi-Agent-ALE-py. Existing ROMS will be overwritten.
Traceback (most recent call last):                                                               
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f0f25e49b50>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s2roms.cc', port=443): Max retries exceeded with url: /s3roms/Atari%202600/P-T/Tetris%202600%20%28Colin%20Hughes%29.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f25e49b50>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaleab/anaconda3/envs/mava-exp/bin/AutoROM", line 15, in <module>
    AutoROM.main(args.accept, specific_dir=args.dir)
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/AutoROM/AutoROM.py", line 237, in main
    manual_downloads(installation_dirs, manual_map, checksum_map)
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/AutoROM/AutoROM.py", line 98, in manual_downloads
    download = requests.get(link)
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/kaleab/anaconda3/envs/mava-exp/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s2roms.cc', port=443): Max retries exceeded with url: /s3roms/Atari%202600/P-T/Tetris%202600%20%28Colin%20Hughes%29.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f25e49b50>: Failed to establish a new connection: [Errno 113] No route to host'))
```

You can see more of the stack trace here - https://github.com/instadeepai/Mava/pull/299/checks?check_run_id=3349654636 .

**Comment by jkterry1** [comment]
Hey, so s2roms.cc is just completely down. We're working on a release of AutoROM that doesn't depend on these somehow, but it looks like it's going to take awhile because no good solution exists. All the ROMs you need are available in this .rar file until things are sorted out though: http://www.atarimania.com/rom_collection_archive_atari_2600_roms.html

**Comment by quantumiracle** [comment]
Extract the ROMS folder from the link by @jkterry1 , and run `python -m atari_py.import_roms <path to ROMS>` solves the problem from my side.

**Comment by KaleabTessera** [comment]
My temp fix for this: 
```
sudo apt-get install unrar
sudo apt-get install unzip -y
wget http://www.atarimania.com/roms/Roms.rar
unrar x Roms.rar
unzip ROMS.zip
python -m atari_py.import_roms ROMS
rm Roms.rar ROMS.zip "HC ROMS.zip"
```

@quantumiracle Doing `python -m atari_py.import_roms Roms.rar` worked in py3.7 & py3.8, but failed in py3.6.

**Comment by jkterry1** [comment]
Fixed in the newest release.
